Feature/new define
sonia-auv/hardware-utility-auv8 pull request #8
Opened 2021-08-08 02:47 UTC by 0x72D0

## Description
New RS485 define

2021-08-12 23:37 UTC, supertoto29 commented on RS485/RS485_definition.h
> +#define SLAVE_IO_ 6
On peut enlever le "_"

2021-08-12 23:38 UTC, supertoto29 requested changes
Enlever le "_"

2021-08-12 23:38 UTC, supertoto29 commented on RS485/RS485_definition.h
> +// define backplane/ESC
Tu me fais changer la backplane. la seule chose qui fonctionnait

2021-08-12 23:49 UTC, 0x72D0 commented on RS485/RS485_definition.h
> +// define backplane/ESC
non je le met comme l'autre

2021-08-13 00:06 UTC, supertoto29 commented on RS485/RS485_definition.h
> +// define backplane/ESC
la backplane est pas programmé avec celui-là encore

2021-08-13 00:07 UTC, supertoto29 approved these changes
LGTM!

2021-08-13 00:08 UTC, merged